apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo
type: Opaque
stringData:
  DB_HOST: mysql-service
  DB_USER: todo_user
  DB_PASSWORD: password
  DB_NAME: mytododb
  SECRET_KEY: "sunbeam"
