# apiVersion: v1
# kind: Service
# metadata:
#   name: todo-service
#   namespace: todo
# spec:
#   selector:
#     app: todo
#   ports:
#     - name: http
#       port: 5000
#       targetPort: 5000
#       nodePort: 30500
#   type: NodePort
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
spec:
  selector:
    app: todo
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP   # Use NodePort only if you want to bypass Ingress
