apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-waf
  namespace: todo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: "waf@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: testwaf.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-service
                port:
                  number: 5000