# k8s/traefik-values.yaml
replicas: 1

service:
  type: LoadBalancer

ports:
  web:
    port: 80
    expose:
      enabled: true
  websecure:
    port: 443
    expose:
      enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

additionalArguments:
  - "--log.level=DEBUG"
  - "--api.dashboard=true"
  - "--providers.kubernetescrd"
  - "--providers.kubernetescrd.namespaces=todo"
  - "--providers.kubernetesingress"
  - "--providers.kubernetesingress.namespaces=todo"
  - "--entrypoints.web.address=:80"